caption_model: newfc
input_json: data/NLP_talk.json
input_fc_dir: data/NLPtalk_fc
input_att_dir: data/NLPtalk_att
input_label_h5: data/NLPtalk_label.h5
learning_rate: 0.0005
learning_rate_decay_start: 0
scheduled_sampling_start: 0
# checkpoint_path: $ckpt_path
# $start_from
language_eval: 1
save_checkpoint_every: 2000
val_images_use: 369

batch_size: 10
max_epochs: 1000